"""add agent_type column

Revision ID: 2c1895a4560d
Revises: 0605815facbc
Create Date: 2025-07-09 14:24:12.589599

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c1895a4560d"
down_revision: Union[str, Sequence[str], None] = "0605815facbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pr_analysis",
        sa.Column(
            "agent_type",
            sa.Enum("ZERO_SHOT_LLM", "ZERO_SHOT_AGENT", name="codereviewagenttype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pr_analysis", "agent_type")
    # ### end Alembic commands ###
