"""initial tables

Revision ID: 3a14da9d5b15
Revises:
Create Date: 2025-07-09 16:33:34.941955

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a14da9d5b15"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pr_analysis",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("repo_url", sa.String(), nullable=True),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("github_token", sa.String(), nullable=True),
        sa.Column("repo", sa.String(), nullable=True),
        sa.Column("repo_owner", sa.String(), nullable=True),
        sa.Column(
            "agent_type",
            sa.Enum(
                "ZERO_SHOT_LLM",
                "ZERO_SHOT_AGENT",
                "MULTI_AGENT",
                name="codereviewagenttype",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="taskstatus"),
            nullable=True,
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "pr_analysis_file",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"], ["pr_analysis.task_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pr_analysis_file_issue",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "STYLE", "BUG", "PERFORMANCE", "BEST_PRACTICE", name="codeissuetype"
            ),
            nullable=True,
        ),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("suggestion", sa.String(), nullable=True),
        sa.Column("is_critical", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"], ["pr_analysis_file.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pr_analysis_file_issue")
    op.drop_table("pr_analysis_file")
    op.drop_table("pr_analysis")
    # ### end Alembic commands ###
